
# Imports
import pandas as pd
import numpy as np
import stouputils as stp
from config import *
from autogen_core import MessageContext, BaseAgent
import requests
import random

# Class
class AgentRandom(BaseAgent):
    def __init__(self) -> None:
        super().__init__(self.__class__.__name__)
        self.msg: Message = Message(origin=self.__class__.__name__)
        
    async def on_message_impl(self, message: Message, ctx: MessageContext) -> None:
        """ Receive a message and send randomly 1 if content is generated by AI, else 0 """
        stp.info(f"AgentRandom: Received message from {message.origin}")

        # Prepare data for the model
        content: str = str(message.content)
        vote: str = json.loads(message.data).get("request")

        if vote == "majoritaire":
            decision = random.choice([1, 0])
            msg = Message(decision, origin=self.__class__.__name__)
        if vote == "borda":
            liste_candidats = ["ai", "human"]
            random.shuffle(liste_candidats)
            nb_points = len(liste_candidats)
            text = ""
            for candidat in liste_candidats:
                text += candidat + " " + str(nb_points) + ","
                nb_points -= 1
            msg = Message(text, origin=self.__class__.__name__)

        # Send back
        await self.send_message(msg, ctx.sender)
        

